name: update todoist

on:
  workflow_dispatch:
  schedule:
    # Runs everyday 2 hour
    - cron: "0 */2 * * *"
      
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""